name: My First Workflow 

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout 
          uses: actions/checkout@v5

        - name: Welcome 
          run: echo "my first github action"

        - name: List Files
          run: ls
        
        - name: Read File 
          run: cat LICENSE
